spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myworld
    username: root
    password: fele
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database: mysql
      show-sql: true
